# Generated by Django 4.0.1 on 2022-01-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%y'),
        ),
    ]
