# Generated by Django 4.0.1 on 2022-01-15 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_webSite', '0002_alter_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
