# Generated by Django 4.0.1 on 2022-01-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0003_alter_courses_by_user_alter_courses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.TextField(max_length=25),
        ),
    ]
