# Generated by Django 4.0.1 on 2022-01-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0004_alter_courses_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
