# Generated by Django 4.0.1 on 2022-01-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_webSite', '0006_alter_courses_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
