# Generated by Django 4.0.1 on 2022-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0007_alter_courses_by_user_alter_courses_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
