# Generated by Django 4.0.1 on 2022-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0009_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_at',
            field=models.DateField(),
        ),
    ]
