# Generated by Django 4.0.1 on 2022-03-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_webSite', '0010_alter_transaction_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userboughtcourse',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses_webSite.courses'),
        ),
    ]
